### ISSUE TITLE
IE11 error with email pattern

### ISSUE THREAD

**Issue by awgul** [cferdinandi/bouncer#7] opened 2018-11-21 01:01 UTC
Hey,

When having an email type filed on IE11 I get this error on keypress or submit:
SCRIPT5017: Syntax error in regular expression
bouncer.js (199,3)

**Comment by cferdinandi** [comment] 2018-11-21 02:42
Aww crap. This appears to be caused by IE11 and lower not allowing anything but a string as the first argument in `new RegExp()`.

I'll get this fixed as soon as I can. Thanks for opening this issue.

**Comment by cferdinandi** [comment] 2018-11-21 02:48
Note for me: pull in RegEx patterns from https://github.com/cferdinandi/bouncer/pull/2/files

**Comment by cferdinandi** [comment] 2018-11-21 04:51
Ok, fixed with v1.1.2. Thanks!

**Closed by cferdinandi** 2018-11-21 04:51 UTC
Labels: bug
